config/routes.rb
Rails.application.routes.draw do
    root 'lists#index'

    resources :lists do
        resources :destinations
    end

    scope 'activities/:activity_id', as: 'activity' do
        resources :activities, only: [:new, :create]
    end 
    
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :destination
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
    belongs_to :list
    has_many :activities
end

app/models/list.rb
class List < ApplicationRecord
    has_one :destination
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_destination
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  def index
    @activities = @destination.activities
  end

  def show
  end

  def new
    @activity = @destination.activities.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @activity = @destination.activities.new(activity_params)

    if @activity.save
      redirect_to [@destination, @activity]
    else
      render :new
    end
  end

  def update
    if @activity.update(activity_params)
      redirect_to [@destination, @activity]
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to list_activities_path
  end

  private
    def set_destination
      @destination = Destination.find(params[:list_id])
    end

    def set_activity
      @activity = Activity.find(params[:id])
    end

    def activity_params
      params.require(:activity).permit(:name, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :set_list, only: [:show, :update, :edit, :destroy]
    
  def index
    @lists = List.all
  end

  def show
    
  end

  def new
    @list = List.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @list = List.new(list_params)
    
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to @list
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private
    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/activities/_form.html.erb
<h1><%= @activities.id ? 'Edit Activity' : 'Create Activity' %></h1>
<br>
<%= form_for [@list, @activities] do |f| %>
  <%= f.label :type %>
  <%= f.text_field :type, required: true, autofocus: true %>
  
  <!-- <%= f.label :body %>
  <%= f.text_area :body, required: true %> -->
  <%= f.submit %>
<% end %>

app/views/activities/edit.html.erb
<h1>Activities#edit</h1>
<p>Find me in app/views/activities/edit.html.erb</p>

app/views/activities/index.html.erb
<h1>Click an Activity To View Content</h1>
<%= link_to 'Create a new activity', new_list_activity_path(@list) %>
<ul>
  <% @activities.each do |activity| %>
    <li><%= link_to activity.name, [@list, acitivty] %></li>
  <% end %>
</ul>

app/views/activities/new.html.erb
<h1>Activities#new</h1>
<!-- <p>Find me in app/views/activities/new.html.erb</p> -->

app/views/activities/show.html.erb
<h1><%= @list.name %> - <%= @activity.name %></h1>
<p><%= @activity.body %></p>
<%= link_to 'Edit Activity', edit_list_activity_path([@list, @activity]) %>
<%= link_to 'Delete Activity', [@list, @activity], method: :delete %>
<%= link_to 'Back To Activities', list_activity_path(@list) %>

app/views/destinations/edit.html.erb
<h1>Destinations#edit</h1>
<p>Find me in app/views/destinations/edit.html.erb</p>

app/views/destinations/index.html.erb
<h1>Destinations#index</h1>
<p>Find me in app/views/destinations/index.html.erb</p>

app/views/destinations/new.html.erb
<h1>Destinations#new</h1>
<p>Find me in app/views/destinations/new.html.erb</p>

app/views/destinations/show.html.erb
<h1>Destinations#show</h1>
<p>Find me in app/views/destinations/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketListV1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<h1><%= @list.id ? 'Edit List' : 'Create Bucket List Entry' %></h1>
<%= form_for @list do |f| %>

<div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
</div>
<br>
<div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, autocomplete: "off" %>
</div>
<br>
<%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Click a List To View Content</h1>
<%= link_to 'Create a New List', new_list_path %>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>New Bucket List Entry</h1>
<!-- <p>Find me in app/views/lists/new.html.erb</p> -->

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<p><%= @list.description %></p>
<br>
<p>What would you like to do?</p>
<%= link_to 'Create Activity Entry', new_list_activity_path(@list) %>
<br>
<%= link_to 'Edit List', edit_list_path(@list) %>
<br>
<%= link_to 'Delete List', @list, method: :delete %>